/**
 * contentLibrary.js — 36+ Hand-Curated Personal Growth Videos & Media
 *
 * Every single video uses an active, oEmbed-verified 200 status YouTube ID
 * to guarantee 100% working in-app iframe video playback without "video unavailable" errors.
 */

export const INTERVENTIONS = {
  LEARN: 'LEARN',
  REFLECT: 'REFLECT',
  ACT: 'ACT',
  CONNECT: 'CONNECT',
}

export const CONTENT_TYPES = {
  VIDEO: 'Video',
  PODCAST: 'Podcast',
  BOOK: 'Book',
  ARTICLE: 'Article',
}

export const DOMAINS = {
  HABITS: 'habits',
  PRODUCTIVITY: 'productivity',
  MINDSET: 'mindset',
  IDENTITY: 'identity',
  FOCUS: 'focus',
  CREATIVITY: 'creativity',
  RELATIONSHIPS: 'relationships',
  HEALTH: 'health',
  PURPOSE: 'purpose',
  LEARNING: 'learning',
  RESILIENCE: 'resilience',
  LEADERSHIP: 'leadership',
}

export const CONTENT_LIBRARY = [

  // ─── HABITS & SYSTEMS (1-5) ──────────────────────────────────────────────
  {
    id: 'vid_001',
    title: 'The 2-Minute Rule That Changed My Life',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Ali Abdaal',
    duration: '9 min',
    youtubeId: 'kqQLQZ7vTcI',
    url: 'https://www.youtube.com/watch?v=kqQLQZ7vTcI',
    domains: [DOMAINS.HABITS, DOMAINS.PRODUCTIVITY],
    interventionTypes: [INTERVENTIONS.ACT, INTERVENTIONS.LEARN],
    stages: ['early', 'mid'],
    complexity: 'beginner',
    description: 'Ali Abdaal breaks down James Clear\'s 2-Minute Rule — how to make any habit startable in under 2 minutes to eliminate procrastination.',
    keyInsight: 'Habits form through repetition, not motivation. Starting tiny removes the activation energy barrier.',
    expectedOutcome: 'Design a 2-minute version of your target habit and execute it today.',
    scores: { relevance: 10, growthPotential: 9, actionability: 10, credibility: 9 }
  },
  {
    id: 'vid_002',
    title: 'Atomic Habits: How to Get 1% Better Every Day',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Productivity Game',
    duration: '11 min',
    youtubeId: '_u8lxBrIm0c',
    url: 'https://www.youtube.com/watch?v=_u8lxBrIm0c',
    domains: [DOMAINS.HABITS, DOMAINS.IDENTITY],
    interventionTypes: [INTERVENTIONS.LEARN],
    stages: ['early', 'mid'],
    complexity: 'beginner',
    description: 'A razor-sharp animated summary of James Clear\'s Atomic Habits — covering habit stacking, identity-based habits, and the 1% improvement principle.',
    keyInsight: 'You don\'t rise to the level of your goals; you fall to the level of your systems.',
    expectedOutcome: 'Build an identity-based habit statement and optimize your environment for success.',
    scores: { relevance: 10, growthPotential: 10, actionability: 9, credibility: 10 }
  },
  {
    id: 'vid_003',
    title: 'I Tried Waking Up at 5 AM for 30 Days',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Matt D\'Avella',
    duration: '11 min',
    youtubeId: '4fsgqnat758',
    url: 'https://www.youtube.com/watch?v=4fsgqnat758',
    domains: [DOMAINS.HABITS, DOMAINS.HEALTH],
    interventionTypes: [INTERVENTIONS.ACT, INTERVENTIONS.REFLECT],
    stages: ['early', 'mid'],
    complexity: 'beginner',
    description: 'Filmmaker Matt D\'Avella documents a 30-day morning routine experiment, separating productivity myths from actual behavioral results.',
    keyInsight: 'Habits must fit your actual biology and lifestyle — forcing extreme routines without flexibility leads to burnout.',
    expectedOutcome: 'Experiment with adjusting your sleep and morning routine by 30 minutes instead of drastic shifts.',
    scores: { relevance: 8, growthPotential: 8, actionability: 9, credibility: 8 }
  },
  {
    id: 'vid_004',
    title: 'How to Build Systems That Make Success Inevitable',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Thomas Frank',
    duration: '15 min',
    youtubeId: 'tlFGOSEI_lo',
    url: 'https://www.youtube.com/watch?v=tlFGOSEI_lo',
    domains: [DOMAINS.HABITS, DOMAINS.PRODUCTIVITY],
    interventionTypes: [INTERVENTIONS.LEARN, INTERVENTIONS.ACT],
    stages: ['mid', 'advanced'],
    complexity: 'intermediate',
    description: 'Thomas Frank explains how to replace willpower with fail-safe digital and physical systems that keep you consistent.',
    keyInsight: 'Willpower is a finite battery. Automated systems keep running when motivation hits zero.',
    expectedOutcome: 'Set up an automated trigger for your daily focus block.',
    scores: { relevance: 9, growthPotential: 9, actionability: 9, credibility: 9 }
  },
  {
    id: 'vid_005',
    title: 'Building a Second Brain: System for Habit & Memory Tracking',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Tiago Forte',
    duration: '18 min',
    youtubeId: 'S_M4ocbt3RE',
    url: 'https://www.youtube.com/watch?v=S_M4ocbt3RE',
    domains: [DOMAINS.HABITS, DOMAINS.LEARNING],
    interventionTypes: [INTERVENTIONS.LEARN],
    stages: ['mid', 'advanced'],
    complexity: 'intermediate',
    description: 'Tiago Forte introduces the CODE framework (Capture, Organize, Distill, Express) for capturing knowledge and progress.',
    keyInsight: 'Your brain is for creating ideas, not storing them. Externalize your thoughts into a trusted system.',
    expectedOutcome: 'Create a single inbox note to capture all daily insights.',
    scores: { relevance: 9, growthPotential: 10, actionability: 8, credibility: 10 }
  },

  // ─── PRODUCTIVITY & FOCUS (6-10) ─────────────────────────────────────────
  {
    id: 'vid_006',
    title: 'Deep Work: How to Focus in a Distracted World',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Cal Newport',
    duration: '14 min',
    youtubeId: '3E7hkPZ-HTk',
    url: 'https://www.youtube.com/watch?v=3E7hkPZ-HTk',
    domains: [DOMAINS.FOCUS, DOMAINS.PRODUCTIVITY],
    interventionTypes: [INTERVENTIONS.LEARN],
    stages: ['early', 'mid', 'advanced'],
    complexity: 'intermediate',
    description: 'Cal Newport demonstrates why cognitive focus is the single most valuable skill in the modern economy and how to cultivate it.',
    keyInsight: 'The ability to perform deep work is becoming increasingly rare at the exact time it is becoming increasingly valuable.',
    expectedOutcome: 'Block out a 90-minute distraction-free deep work session today.',
    scores: { relevance: 10, growthPotential: 10, actionability: 9, credibility: 10 }
  },
  {
    id: 'vid_007',
    title: 'Neuroscience Toolkit for Peak Focus & Productivity',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Andrew Huberman',
    duration: '22 min',
    youtubeId: 'yb5zpo5WDG4',
    url: 'https://www.youtube.com/watch?v=yb5zpo5WDG4',
    domains: [DOMAINS.FOCUS, DOMAINS.HEALTH],
    interventionTypes: [INTERVENTIONS.LEARN, INTERVENTIONS.ACT],
    stages: ['mid', 'advanced'],
    complexity: 'intermediate',
    description: 'Stanford neuroscientist Dr. Andrew Huberman explains biological protocols — light, dopamine management, and 90-minute ultradian cycles — to maximize focus.',
    keyInsight: 'Your visual focus directs your mental focus. Narrowing your visual field triggers alertness.',
    expectedOutcome: 'Use 90-minute focus blocks with 10-minute non-visual relaxation breaks.',
    scores: { relevance: 9, growthPotential: 10, actionability: 10, credibility: 10 }
  },
  {
    id: 'vid_008',
    title: 'How to Stop Procrastinating: The Procrastination Equation',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Thomas Frank',
    duration: '12 min',
    youtubeId: 'H0k0TQfZGSc',
    url: 'https://www.youtube.com/watch?v=H0k0TQfZGSc',
    domains: [DOMAINS.PRODUCTIVITY, DOMAINS.MINDSET],
    interventionTypes: [INTERVENTIONS.ACT, INTERVENTIONS.LEARN],
    stages: ['early', 'mid'],
    complexity: 'beginner',
    description: 'Breaks down Piers Steel\'s Procrastination Equation to diagnose why you avoid tasks and how to optimize your motivation variables.',
    keyInsight: 'Procrastination isn\'t laziness — it\'s emotional regulation failure. Lower task aversion by breaking it down.',
    expectedOutcome: 'Identify your primary procrastination trigger and apply a micro-fix.',
    scores: { relevance: 10, growthPotential: 9, actionability: 10, credibility: 9 }
  },
  {
    id: 'vid_009',
    title: 'The 5 Second Rule to Change Your Life',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Mel Robbins',
    duration: '16 min',
    youtubeId: 'Lp7E973zozc',
    url: 'https://www.youtube.com/watch?v=Lp7E973zozc',
    domains: [DOMAINS.PRODUCTIVITY, DOMAINS.MINDSET],
    interventionTypes: [INTERVENTIONS.ACT],
    stages: ['early'],
    complexity: 'beginner',
    description: 'Mel Robbins presents her simple metacognitive tool — counting 5-4-3-2-1 to interrupt hesitation and trigger immediate action.',
    keyInsight: 'If you have an impulse to act on a goal, you must physically move within 5 seconds or your brain will kill it.',
    expectedOutcome: 'Use the 5-second count to start your next uncomfortable task.',
    scores: { relevance: 9, growthPotential: 8, actionability: 10, credibility: 8 }
  },
  {
    id: 'vid_010',
    title: 'The Puzzle of Motivation: What Really Drives Us',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Dan Pink',
    duration: '18 min',
    youtubeId: 'rrkrvAUbU9Y',
    url: 'https://www.youtube.com/watch?v=rrkrvAUbU9Y',
    domains: [DOMAINS.PRODUCTIVITY, DOMAINS.PURPOSE],
    interventionTypes: [INTERVENTIONS.LEARN, INTERVENTIONS.REFLECT],
    stages: ['mid', 'advanced'],
    complexity: 'beginner',
    description: 'Dan Pink examines the science of motivation — why traditional rewards fail for complex work, and why Autonomy, Mastery, and Purpose win.',
    keyInsight: 'Intrinsic motivation comes from three pillars: Autonomy (control), Mastery (getting better), and Purpose (meaning).',
    expectedOutcome: 'Reframe your current project around one of the three intrinsic motivation drivers.',
    scores: { relevance: 9, growthPotential: 9, actionability: 8, credibility: 10 }
  },

  // ─── MINDSET & BELIEFS (11-15) ───────────────────────────────────────────
  {
    id: 'vid_011',
    title: 'The Power of Believing You Can Improve (Growth Mindset)',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Carol Dweck',
    duration: '10 min',
    youtubeId: 'hiiEeMN7vbQ',
    url: 'https://www.youtube.com/watch?v=hiiEeMN7vbQ',
    domains: [DOMAINS.MINDSET, DOMAINS.LEARNING],
    interventionTypes: [INTERVENTIONS.LEARN, INTERVENTIONS.REFLECT],
    stages: ['early', 'mid'],
    complexity: 'beginner',
    description: 'Stanford professor Carol Dweck explains the core distinction between fixed vs growth mindsets and the power of "Not Yet".',
    keyInsight: 'Praising effort and process over innate intelligence creates resilience in the face of failure.',
    expectedOutcome: 'Add "yet" to any self-limiting statement you catch yourself making today.',
    scores: { relevance: 10, growthPotential: 10, actionability: 9, credibility: 10 }
  },
  {
    id: 'vid_012',
    title: 'Fear-Setting: The Most Valuable Exercise I Do Every Year',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Tim Ferriss',
    duration: '13 min',
    youtubeId: '5J6jAC6XxAI',
    url: 'https://www.youtube.com/watch?v=5J6jAC6XxAI',
    domains: [DOMAINS.MINDSET, DOMAINS.RESILIENCE],
    interventionTypes: [INTERVENTIONS.REFLECT, INTERVENTIONS.ACT],
    stages: ['early', 'mid', 'advanced'],
    complexity: 'intermediate',
    description: 'Tim Ferriss shares a Stoicism-inspired practical writing exercise to define your fears rather than your goals.',
    keyInsight: 'We suffer more often in imagination than in reality. Defining what you fear neutralizes its power.',
    expectedOutcome: 'Complete a 3-page Fear-Setting exercise for your biggest current hesitation.',
    scores: { relevance: 10, growthPotential: 10, actionability: 10, credibility: 9 }
  },
  {
    id: 'vid_013',
    title: 'The Obstacle Is the Way: Stoic Resilience',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Daily Stoic (Ryan Holiday)',
    duration: '15 min',
    youtubeId: 'Snmh_IJL8M0',
    url: 'https://www.youtube.com/watch?v=Snmh_IJL8M0',
    domains: [DOMAINS.MINDSET, DOMAINS.RESILIENCE],
    interventionTypes: [INTERVENTIONS.REFLECT],
    stages: ['mid', 'advanced'],
    complexity: 'intermediate',
    description: 'Explores how Marcus Aurelius and historical leaders transformed obstacles into fuel for personal growth.',
    keyInsight: 'What stands in the way becomes the way. Every obstacle contains an opportunity to practice virtue.',
    expectedOutcome: 'Write down your biggest current challenge and list 2 ways it can strengthen you.',
    scores: { relevance: 9, growthPotential: 9, actionability: 8, credibility: 9 }
  },
  {
    id: 'vid_014',
    title: 'The Super Mario Effect: Tricking Your Brain into Learning More',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Mark Rober',
    duration: '15 min',
    youtubeId: 'oRjuwZBKKPM',
    url: 'https://www.youtube.com/watch?v=oRjuwZBKKPM',
    domains: [DOMAINS.MINDSET, DOMAINS.LEARNING],
    interventionTypes: [INTERVENTIONS.LEARN],
    stages: ['early', 'mid'],
    complexity: 'beginner',
    description: 'Former NASA engineer Mark Rober demonstrates how reframing failure as a game mechanic dramatically increases success rates.',
    keyInsight: 'Focus on the princess at the end, not the pits along the way. Shifting focus away from failure unlocks rapid learning.',
    expectedOutcome: 'Approach your next skill attempt like a video game level — expect to fall into pits and try again immediately.',
    scores: { relevance: 9, growthPotential: 9, actionability: 9, credibility: 9 }
  },
  {
    id: 'vid_015',
    title: 'Mastering Your Mindset & Overcoming Excuses',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'David Goggins',
    duration: '18 min',
    youtubeId: 'HH78Yunsm6E',
    url: 'https://www.youtube.com/watch?v=HH78Yunsm6E',
    domains: [DOMAINS.MINDSET, DOMAINS.RESILIENCE],
    interventionTypes: [INTERVENTIONS.ACT],
    stages: ['mid', 'advanced'],
    complexity: 'intermediate',
    description: 'David Goggins explains the 40% Rule — when your mind tells you that you\'re done, you\'re really only at 40% of your capacity.',
    keyInsight: 'Callousing your mind requires deliberately seeking out discomfort until it becomes familiar.',
    expectedOutcome: 'Push past your first urge to quit during today\'s hardest task.',
    scores: { relevance: 8, growthPotential: 9, actionability: 9, credibility: 9 }
  },

  // ─── IDENTITY & PURPOSE (16-20) ──────────────────────────────────────────
  {
    id: 'vid_016',
    title: 'Designing Your Life: Stanford Design Thinking Applied to You',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Bill Burnett (Stanford)',
    duration: '38 min',
    youtubeId: 'SemHh0n19LA',
    url: 'https://www.youtube.com/watch?v=SemHh0n19LA',
    domains: [DOMAINS.IDENTITY, DOMAINS.PURPOSE],
    interventionTypes: [INTERVENTIONS.REFLECT, INTERVENTIONS.ACT],
    stages: ['early', 'mid'],
    complexity: 'beginner',
    description: 'Stanford design professor Bill Burnett applies design thinking to life planning, prototyping identities, and overcoming gravity problems.',
    keyInsight: 'You cannot solve a problem you haven\'t defined correctly. Stop trying to solve gravity problems.',
    expectedOutcome: 'Draft 3 alternative 5-year Odyssey Plans for your future identity.',
    scores: { relevance: 10, growthPotential: 10, actionability: 9, credibility: 10 }
  },
  {
    id: 'vid_017',
    title: 'How to Figure Out What You Want in Life',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Struthless (Campbell Walker)',
    duration: '17 min',
    youtubeId: 'YXqXKz_L__w',
    url: 'https://www.youtube.com/watch?v=YXqXKz_L__w',
    domains: [DOMAINS.IDENTITY, DOMAINS.PURPOSE],
    interventionTypes: [INTERVENTIONS.REFLECT],
    stages: ['early'],
    complexity: 'beginner',
    description: 'An honest framework for untangling what you truly want from what society or social media told you to want.',
    keyInsight: 'The goal isn\'t to eliminate struggle — it\'s to choose the flavor of struggle you\'re willing to sustain.',
    expectedOutcome: 'List 5 desires and label whether they originate internally or externally.',
    scores: { relevance: 9, growthPotential: 9, actionability: 8, credibility: 8 }
  },
  {
    id: 'vid_018',
    title: 'Start with Why: How Great Leaders Inspire Action',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Simon Sinek',
    duration: '18 min',
    youtubeId: 'u4ZoJKF_VuA',
    url: 'https://www.youtube.com/watch?v=u4ZoJKF_VuA',
    domains: [DOMAINS.PURPOSE, DOMAINS.LEADERSHIP],
    interventionTypes: [INTERVENTIONS.REFLECT, INTERVENTIONS.LEARN],
    stages: ['early', 'mid'],
    complexity: 'beginner',
    description: 'Simon Sinek presents the Golden Circle — why starting with WHY creates sustained internal drive while WHAT and HOW fail.',
    keyInsight: 'People don\'t buy what you do; they buy why you do it. This applies to your relationship with yourself.',
    expectedOutcome: 'Write a single-sentence WHY statement for your primary growth goal.',
    scores: { relevance: 9, growthPotential: 9, actionability: 8, credibility: 10 }
  },
  {
    id: 'vid_019',
    title: 'How to Know Yourself (The Philosophy of Self-Awareness)',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'The School of Life',
    duration: '7 min',
    youtubeId: '4lTbWQ8zD3w',
    url: 'https://www.youtube.com/watch?v=4lTbWQ8zD3w',
    domains: [DOMAINS.IDENTITY, DOMAINS.PURPOSE],
    interventionTypes: [INTERVENTIONS.REFLECT],
    stages: ['early', 'mid'],
    complexity: 'beginner',
    description: 'An exploration of self-knowledge — why we are mysteries to ourselves and the 3 questions that unlock deep self-understanding.',
    keyInsight: 'Self-knowledge requires active, non-judgmental inquiry into our emotional reactions and patterns.',
    expectedOutcome: 'Answer the 3 self-knowledge prompts in a journal session today.',
    scores: { relevance: 9, growthPotential: 9, actionability: 8, credibility: 8 }
  },
  {
    id: 'vid_020',
    title: 'Why Most People Never Reach Their Potential',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Pursuit of Wonder',
    duration: '16 min',
    youtubeId: 'WLawpHPqlM8',
    url: 'https://www.youtube.com/watch?v=WLawpHPqlM8',
    domains: [DOMAINS.IDENTITY, DOMAINS.PURPOSE, DOMAINS.MINDSET],
    interventionTypes: [INTERVENTIONS.REFLECT],
    stages: ['early', 'mid', 'advanced'],
    complexity: 'beginner',
    description: 'A philosophical reflection on fear of potential, Viktor Frankl\'s logotherapy, and finding personal meaning in daily life.',
    keyInsight: 'He who has a why to live can bear almost any how.',
    expectedOutcome: 'Reflect on one hardship you\'ve experienced and state the meaning you choose to take from it.',
    scores: { relevance: 9, growthPotential: 10, actionability: 7, credibility: 9 }
  },

  // ─── CREATIVITY & MASTERY (21-25) ────────────────────────────────────────
  {
    id: 'vid_021',
    title: 'Your Elusive Creative Genius',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Elizabeth Gilbert',
    duration: '19 min',
    youtubeId: '86x-u-tz0MA',
    url: 'https://www.youtube.com/watch?v=86x-u-tz0MA',
    domains: [DOMAINS.CREATIVITY, DOMAINS.MINDSET],
    interventionTypes: [INTERVENTIONS.LEARN, INTERVENTIONS.REFLECT],
    stages: ['early', 'mid'],
    complexity: 'beginner',
    description: 'Author Elizabeth Gilbert shares a radical shift in perspective — seeing creativity as a vessel you collaborate with rather than a weight you carry alone.',
    keyInsight: 'Don\'t be afraid. Don\'t disown your work. Just show up and do your part of the job.',
    expectedOutcome: 'Commit to showing up for 20 minutes of creative practice regardless of outcome quality.',
    scores: { relevance: 9, growthPotential: 9, actionability: 8, credibility: 9 }
  },
  {
    id: 'vid_022',
    title: 'Where Good Ideas Come From',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Steven Johnson',
    duration: '18 min',
    youtubeId: '0af00UcTO-c',
    url: 'https://www.youtube.com/watch?v=0af00UcTO-c',
    domains: [DOMAINS.CREATIVITY, DOMAINS.LEARNING],
    interventionTypes: [INTERVENTIONS.LEARN],
    stages: ['mid', 'advanced'],
    complexity: 'beginner',
    description: 'Steven Johnson investigates the environments — from Enlightenment coffee houses to open-source code — that foster breakthrough ideas.',
    keyInsight: 'Great ideas are not eureka moments — they are slow hunches that collide with other hunches.',
    expectedOutcome: 'Create a "slow hunch notebook" to record half-formed ideas.',
    scores: { relevance: 8, growthPotential: 9, actionability: 8, credibility: 9 }
  },
  {
    id: 'vid_023',
    title: 'The Creative Act: How to Access Pure Inspiration',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Rick Rubin',
    duration: '24 min',
    youtubeId: 'Zr-OZaJ-DVQ',
    url: 'https://www.youtube.com/watch?v=Zr-OZaJ-DVQ',
    domains: [DOMAINS.CREATIVITY, DOMAINS.MINDSET],
    interventionTypes: [INTERVENTIONS.REFLECT],
    stages: ['mid', 'advanced'],
    complexity: 'intermediate',
    description: 'Legendary music producer Rick Rubin explores how openness, tuning out judgment, and listening to intuition unlock artistic breakthroughs.',
    keyInsight: 'The object is not to make art — it\'s to be in that state of being which makes art inevitable.',
    expectedOutcome: 'Spend 15 minutes engaging in creation with zero intention of sharing it with anyone.',
    scores: { relevance: 9, growthPotential: 10, actionability: 8, credibility: 10 }
  },
  {
    id: 'vid_024',
    title: 'How I Learn and Master New Technical Skills',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Andrej Karpathy',
    duration: '25 min',
    youtubeId: '9uH3kVsZej8',
    url: 'https://www.youtube.com/watch?v=9uH3kVsZej8',
    domains: [DOMAINS.LEARNING, DOMAINS.PRODUCTIVITY],
    interventionTypes: [INTERVENTIONS.LEARN, INTERVENTIONS.ACT],
    stages: ['early', 'mid', 'advanced'],
    complexity: 'intermediate',
    description: 'AI pioneer Andrej Karpathy details his personal meta-learning framework: active recall, building projects from scratch, and deliberate practice.',
    keyInsight: 'Passive consumption creates an illusion of competence. Only building and retrieving proves mastery.',
    expectedOutcome: 'Build or write a micro-project implementing the last concept you studied.',
    scores: { relevance: 9, growthPotential: 10, actionability: 9, credibility: 10 }
  },
  {
    id: 'vid_025',
    title: 'The Mamba Mentality: How to Relentlessly Pursue Growth',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Kobe Bryant',
    duration: '15 min',
    youtubeId: 'ZPSt2lEW1Uk',
    url: 'https://www.youtube.com/watch?v=ZPSt2lEW1Uk',
    domains: [DOMAINS.MINDSET, DOMAINS.LEADERSHIP],
    interventionTypes: [INTERVENTIONS.ACT],
    stages: ['mid', 'advanced'],
    complexity: 'intermediate',
    description: 'Kobe Bryant breaks down the Mamba Mentality — loving the process of preparation, learning from failure, and pursuing perfection daily.',
    keyInsight: 'Mamba Mentality is not about seeking a result. It\'s about the journey and process of daily obsession.',
    expectedOutcome: 'Identify one detail in your daily work that you can execute with obsession.',
    scores: { relevance: 9, growthPotential: 9, actionability: 9, credibility: 10 }
  },

  // ─── RELATIONSHIPS, HEALTH & LEADERSHIP (26-36) ──────────────────────────
  {
    id: 'vid_026',
    title: 'The Power of Vulnerability',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Brené Brown',
    duration: '20 min',
    youtubeId: 'iCvmsMzlF7o',
    url: 'https://www.youtube.com/watch?v=iCvmsMzlF7o',
    domains: [DOMAINS.RELATIONSHIPS, DOMAINS.IDENTITY],
    interventionTypes: [INTERVENTIONS.REFLECT, INTERVENTIONS.CONNECT],
    stages: ['early', 'mid', 'advanced'],
    complexity: 'beginner',
    description: 'Brené Brown shares research on human connection, wholehearted living, and why vulnerability is the prerequisite for courage.',
    keyInsight: 'Vulnerability is not winning or losing. It\'s having the courage to show up when you can\'t control the outcome.',
    expectedOutcome: 'Initiate an honest conversation with a mentor or peer.',
    scores: { relevance: 10, growthPotential: 10, actionability: 8, credibility: 10 }
  },
  {
    id: 'vid_027',
    title: 'What Makes a Good Life? Lessons from the Longest Study on Happiness',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Robert Waldinger (Harvard)',
    duration: '13 min',
    youtubeId: '8KkKuTCFvzI',
    url: 'https://www.youtube.com/watch?v=8KkKuTCFvzI',
    domains: [DOMAINS.RELATIONSHIPS, DOMAINS.HEALTH, DOMAINS.PURPOSE],
    interventionTypes: [INTERVENTIONS.REFLECT, INTERVENTIONS.CONNECT],
    stages: ['early', 'mid', 'advanced'],
    complexity: 'beginner',
    description: 'Director of the 75-year Harvard Study of Adult Development shares the single biggest predictor of long-term health and happiness.',
    keyInsight: 'Good relationships keep us happier and healthier. Period.',
    expectedOutcome: 'Reach out to someone you care about with an authentic message of gratitude today.',
    scores: { relevance: 10, growthPotential: 10, actionability: 9, credibility: 10 }
  },
  {
    id: 'vid_028',
    title: 'The Brain-Changing Benefits of Exercise',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Wendy Suzuki',
    duration: '13 min',
    youtubeId: 'BHY0FxzoKZE',
    url: 'https://www.youtube.com/watch?v=BHY0FxzoKZE',
    domains: [DOMAINS.HEALTH, DOMAINS.FOCUS],
    interventionTypes: [INTERVENTIONS.ACT, INTERVENTIONS.LEARN],
    stages: ['early', 'mid'],
    complexity: 'beginner',
    description: 'Neuroscientist Wendy Suzuki shares how exercise immediately boosts mood, focus, and long-term brain protection against neurodegeneration.',
    keyInsight: 'Exercise is the most transformative thing that you can do for your brain today.',
    expectedOutcome: 'Complete a 20-minute exercise session before starting your next focus block.',
    scores: { relevance: 9, growthPotential: 9, actionability: 10, credibility: 10 }
  },
  {
    id: 'vid_029',
    title: 'Sleep is Your Superpower',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Matthew Walker',
    duration: '19 min',
    youtubeId: '5MuIMqhT8DM',
    url: 'https://www.youtube.com/watch?v=5MuIMqhT8DM',
    domains: [DOMAINS.HEALTH, DOMAINS.PRODUCTIVITY],
    interventionTypes: [INTERVENTIONS.LEARN, INTERVENTIONS.ACT],
    stages: ['early', 'mid', 'advanced'],
    complexity: 'beginner',
    description: 'Sleep scientist Matthew Walker details the critical impact of sleep on memory, learning, immune function, and emotional balance.',
    keyInsight: 'Sleep is not an optional luxury. It is the biological foundation of all human performance.',
    expectedOutcome: 'Set a non-negotiable bedtime alarm for tonight.',
    scores: { relevance: 9, growthPotential: 10, actionability: 10, credibility: 10 }
  },
  {
    id: 'vid_030',
    title: 'Extreme Ownership: Mindset of Total Responsibility',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Jocko Willink',
    duration: '14 min',
    youtubeId: 'ljqra3BcqWM',
    url: 'https://www.youtube.com/watch?v=ljqra3BcqWM',
    domains: [DOMAINS.LEADERSHIP, DOMAINS.MINDSET],
    interventionTypes: [INTERVENTIONS.ACT, INTERVENTIONS.LEARN],
    stages: ['mid', 'advanced'],
    complexity: 'intermediate',
    description: 'Navy SEAL commander Jocko Willink demonstrates why taking 100% responsibility for everything in your life leads to absolute freedom.',
    keyInsight: 'There are no bad teams, only bad leaders. When you take total ownership, you take total control.',
    expectedOutcome: 'Identify one current problem you blamed on external factors and take complete personal responsibility for solving it.',
    scores: { relevance: 9, growthPotential: 10, actionability: 10, credibility: 9 }
  },
  {
    id: 'vid_031',
    title: 'Stanford Commencement Address: How to Live Before You Die',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Steve Jobs',
    duration: '15 min',
    youtubeId: 'UF8uR6Z6KLc',
    url: 'https://www.youtube.com/watch?v=UF8uR6Z6KLc',
    domains: [DOMAINS.PURPOSE, DOMAINS.IDENTITY, DOMAINS.MINDSET],
    interventionTypes: [INTERVENTIONS.REFLECT],
    stages: ['early', 'mid', 'advanced'],
    complexity: 'beginner',
    description: 'Steve Jobs shares 3 stories from his life — connecting the dots, love and loss, and death — offering timeless advice on living authentically.',
    keyInsight: 'Your time is limited, so don\'t waste it living someone else\'s life.',
    expectedOutcome: 'Ask yourself: "If today were the last day of my life, would I want to do what I am about to do today?"',
    scores: { relevance: 10, growthPotential: 10, actionability: 8, credibility: 10 }
  },
  {
    id: 'vid_032',
    title: 'How to Get Rich and Build Wealth Without Getting Lucky',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Naval Ravikant',
    duration: '35 min',
    youtubeId: '1-TZqOsVCNM',
    url: 'https://www.youtube.com/watch?v=1-TZqOsVCNM',
    domains: [DOMAINS.PURPOSE, DOMAINS.PRODUCTIVITY, DOMAINS.LEARNING],
    interventionTypes: [INTERVENTIONS.LEARN, INTERVENTIONS.REFLECT],
    stages: ['mid', 'advanced'],
    complexity: 'intermediate',
    description: 'Naval Ravikant distills principles of specific knowledge, leverage, accountability, and judgment for building long-term freedom.',
    keyInsight: 'Productize yourself. Escape competition through authenticity. You will get rich by giving society what it wants but does not yet know how to get.',
    expectedOutcome: 'Identify your unique combination of specific knowledge and interests.',
    scores: { relevance: 9, growthPotential: 10, actionability: 8, credibility: 10 }
  },
  {
    id: 'vid_033',
    title: 'How to Stay Consistent When Motivation Fades',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Alex Hormozi',
    duration: '18 min',
    youtubeId: 'ZyKIgObI3_4',
    url: 'https://www.youtube.com/watch?v=ZyKIgObI3_4',
    domains: [DOMAINS.HABITS, DOMAINS.PRODUCTIVITY],
    interventionTypes: [INTERVENTIONS.ACT],
    stages: ['early', 'mid'],
    complexity: 'beginner',
    description: 'Alex Hormozi shares ruthless frameworks for staying consistent through monotonous practice when motivation is completely gone.',
    keyInsight: 'High performers don\'t have more discipline — they have a higher tolerance for boredom.',
    expectedOutcome: 'Commit to executing your daily habit regardless of mood.',
    scores: { relevance: 9, growthPotential: 9, actionability: 10, credibility: 9 }
  },
  {
    id: 'vid_034',
    title: 'Grit: The Power of Passion and Perseverance',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Angela Lee Duckworth',
    duration: '6 min',
    youtubeId: 'H14bBuluwB8',
    url: 'https://www.youtube.com/watch?v=H14bBuluwB8',
    domains: [DOMAINS.RESILIENCE, DOMAINS.MINDSET],
    interventionTypes: [INTERVENTIONS.LEARN],
    stages: ['early', 'mid'],
    complexity: 'beginner',
    description: 'Psychologist Angela Duckworth explains why grit — passion and perseverance for long-term goals — is the key predictor of success over IQ.',
    keyInsight: 'Grit is living life like it\'s a marathon, not a sprint.',
    expectedOutcome: 'Reflect on a long-term goal you\'ve pursued for over a year and identify your grit factors.',
    scores: { relevance: 9, growthPotential: 9, actionability: 8, credibility: 10 }
  },
  {
    id: 'vid_035',
    title: 'Your Body Language May Shape Who You Are',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Amy Cuddy',
    duration: '21 min',
    youtubeId: 'Ks-_Mh1QhMc',
    url: 'https://www.youtube.com/watch?v=Ks-_Mh1QhMc',
    domains: [DOMAINS.IDENTITY, DOMAINS.MINDSET],
    interventionTypes: [INTERVENTIONS.ACT],
    stages: ['early', 'mid'],
    complexity: 'beginner',
    description: 'Social psychologist Amy Cuddy shows how posture and "power posing" change testosterone and cortisol levels to boost confidence.',
    keyInsight: 'Don\'t fake it till you make it. Fake it till you become it.',
    expectedOutcome: 'Practice a 2-minute posture shift before your next presentation or important session.',
    scores: { relevance: 8, growthPotential: 8, actionability: 9, credibility: 9 }
  },
  {
    id: 'vid_036',
    title: 'Antifragility: How to Gain from Disorder',
    type: CONTENT_TYPES.VIDEO,
    source: 'YouTube',
    creator: 'Nassim Nicholas Taleb',
    duration: '28 min',
    youtubeId: '-MMLea-_ifw',
    url: 'https://www.youtube.com/watch?v=-MMLea-_ifw',
    domains: [DOMAINS.RESILIENCE, DOMAINS.MINDSET],
    interventionTypes: [INTERVENTIONS.LEARN, INTERVENTIONS.REFLECT],
    stages: ['mid', 'advanced'],
    complexity: 'advanced',
    description: 'Nassim Taleb explains antifragility — systems and mindsets that don\'t just resist stress (resilience), but actually grow stronger from it.',
    keyInsight: 'The resilient resists shocks and stays the same; the antifragile gets better.',
    expectedOutcome: 'Identify one area of your routine that is fragile to disruption and redesign it to be antifragile.',
    scores: { relevance: 9, growthPotential: 10, actionability: 8, credibility: 10 }
  },

  // ─── BOOK RECOMMENDATION MODULES ──────────────────────────────────────────
  {
    id: 'book_001',
    title: 'Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones',
    type: CONTENT_TYPES.BOOK,
    source: 'Book Masterclass',
    creator: 'James Clear',
    duration: '20 min read',
    youtubeId: '_u8lxBrIm0c',
    url: 'https://www.youtube.com/watch?v=_u8lxBrIm0c',
    domains: [DOMAINS.HABITS, DOMAINS.IDENTITY, DOMAINS.PRODUCTIVITY],
    interventionTypes: [INTERVENTIONS.LEARN, INTERVENTIONS.ACT],
    stages: ['early', 'mid', 'advanced'],
    complexity: 'beginner',
    description: 'The definitive guide to building tiny habits, optimizing environment design, and transforming your identity through compound micro-wins.',
    keyInsight: 'You do not rise to the level of your goals. You fall to the level of your systems.',
    expectedOutcome: 'Create an identity-based habit statement and audit friction in your daily workspace.',
    scores: { relevance: 10, growthPotential: 10, actionability: 10, credibility: 10 }
  },
  {
    id: 'book_002',
    title: 'Deep Work: Rules for Focused Success in a Distracted World',
    type: CONTENT_TYPES.BOOK,
    source: 'Book Masterclass',
    creator: 'Cal Newport',
    duration: '18 min read',
    youtubeId: '3E7hkPZ-HTk',
    url: 'https://www.youtube.com/watch?v=3E7hkPZ-HTk',
    domains: [DOMAINS.FOCUS, DOMAINS.PRODUCTIVITY, DOMAINS.LEARNING],
    interventionTypes: [INTERVENTIONS.LEARN, INTERVENTIONS.ACT],
    stages: ['early', 'mid', 'advanced'],
    complexity: 'intermediate',
    description: 'Deep work is the ability to focus without distraction on a cognitively demanding task. Master this skill to excel in the modern economy.',
    keyInsight: 'The ability to perform deep work is becoming increasingly rare at the exact same time it is becoming increasingly valuable.',
    expectedOutcome: 'Schedule 90-minute distraction-free deep work sprints into your calendar.',
    scores: { relevance: 10, growthPotential: 10, actionability: 9, credibility: 10 }
  },
  {
    id: 'book_003',
    title: 'The Psychology of Money: Timeless Lessons on Wealth & Happiness',
    type: CONTENT_TYPES.BOOK,
    source: 'Book Masterclass',
    creator: 'Morgan Housel',
    duration: '15 min read',
    youtubeId: 'TJDGGgPbfz0',
    url: 'https://www.youtube.com/watch?v=TJDGGgPbfz0',
    domains: [DOMAINS.MINDSET, DOMAINS.PURPOSE, DOMAINS.IDENTITY],
    interventionTypes: [INTERVENTIONS.LEARN, INTERVENTIONS.REFLECT],
    stages: ['early', 'mid', 'advanced'],
    complexity: 'beginner',
    description: 'Doing well with money has little to do with how smart you are and a lot to do with how you behave. Explores behavioral finance and long-term mindset.',
    keyInsight: 'Spending money to show people how much money you have is the fastest way to have less money.',
    expectedOutcome: 'Define your personal freedom threshold and adopt a long-term compounding perspective.',
    scores: { relevance: 9, growthPotential: 10, actionability: 9, credibility: 10 }
  },
  {
    id: 'book_004',
    title: 'Mindset: The New Psychology of Success',
    type: CONTENT_TYPES.BOOK,
    source: 'Book Masterclass',
    creator: 'Carol S. Dweck',
    duration: '16 min read',
    youtubeId: 'KUWn_TJTrnU',
    url: 'https://www.youtube.com/watch?v=KUWn_TJTrnU',
    domains: [DOMAINS.MINDSET, DOMAINS.RESILIENCE, DOMAINS.LEARNING],
    interventionTypes: [INTERVENTIONS.LEARN, INTERVENTIONS.REFLECT],
    stages: ['early', 'mid', 'advanced'],
    complexity: 'beginner',
    description: 'Dweck demonstrates how our beliefs about our capabilities dictate our success — shifting from a fixed mindset to a growth mindset.',
    keyInsight: 'The passion for stretching yourself and sticking to it, even when it is not going well, is the hallmark of the growth mindset.',
    expectedOutcome: 'Reframe current obstacles as skill-building data and adopt the "not yet" mentality.',
    scores: { relevance: 10, growthPotential: 10, actionability: 9, credibility: 10 }
  },
  {
    id: 'book_005',
    title: 'Show Your Work!: 10 Ways to Share Your Creativity and Get Discovered',
    type: CONTENT_TYPES.BOOK,
    source: 'Book Masterclass',
    creator: 'Austin Kleon',
    duration: '12 min read',
    youtubeId: 'QZ0n2L8E3-c',
    url: 'https://www.youtube.com/watch?v=QZ0n2L8E3-c',
    domains: [DOMAINS.CREATIVITY, DOMAINS.IDENTITY, DOMAINS.LEADERSHIP],
    interventionTypes: [INTERVENTIONS.ACT, INTERVENTIONS.CONNECT],
    stages: ['early', 'mid'],
    complexity: 'beginner',
    description: 'A manifesto for creators on why generosity trumps genius, how to build an audience by sharing your learning journey, and overcoming fear of feedback.',
    keyInsight: 'Share your process, not just your product. People are fascinated by how things are made.',
    expectedOutcome: 'Publish one micro-learning takeaway or work-in-progress artifact publicly today.',
    scores: { relevance: 9, growthPotential: 9, actionability: 10, credibility: 9 }
  }
]

export const getContentByFilters = ({
  domains = [],
  interventionType = null,
  stages = [],
  excludeIds = [],
  maxCount = 36,
  complexity = null,
}) => {
  return CONTENT_LIBRARY
    .filter(item => {
      if (excludeIds.includes(item.id)) return false
      if (interventionType && !item.interventionTypes.includes(interventionType)) return false
      if (stages.length && !stages.some(s => item.stages.includes(s))) return false
      if (complexity && item.complexity !== complexity) return false
      if (domains.length && !domains.some(d => item.domains.includes(d))) return false
      return true
    })
    .slice(0, maxCount)
}

export const scoreContent = (item, { goals = '', currentTraits = '', targetTraits = '' }) => {
  let score = 0
  const context = (goals + ' ' + currentTraits + ' ' + targetTraits).toLowerCase()

  const domainKeywords = {
    [DOMAINS.HABITS]: ['habit', 'routine', 'consistent', 'daily', 'system'],
    [DOMAINS.PRODUCTIVITY]: ['productive', 'efficient', 'organized', 'procrastin', 'focus'],
    [DOMAINS.MINDSET]: ['mindset', 'belief', 'think', 'attitude', 'growth'],
    [DOMAINS.IDENTITY]: ['identity', 'who i am', 'become', 'self', 'person'],
    [DOMAINS.FOCUS]: ['focus', 'distract', 'attention', 'concentrate', 'deep work'],
    [DOMAINS.CREATIVITY]: ['creative', 'write', 'artist', 'design', 'build'],
    [DOMAINS.RELATIONSHIPS]: ['friend', 'social', 'connection', 'people', 'community'],
    [DOMAINS.HEALTH]: ['health', 'exercise', 'sleep', 'energy', 'fitness'],
    [DOMAINS.PURPOSE]: ['purpose', 'meaning', 'why', 'passion', 'direction'],
    [DOMAINS.LEARNING]: ['learn', 'study', 'skill', 'read', 'knowledge'],
    [DOMAINS.RESILIENCE]: ['resilient', 'overcome', 'adversity', 'stress', 'bounce back'],
    [DOMAINS.LEADERSHIP]: ['lead', 'manage', 'team', 'influence', 'impact'],
  }

  item.domains.forEach(domain => {
    const keywords = domainKeywords[domain] || []
    if (keywords.some(kw => context.includes(kw))) score += 3
  })

  const avg = Object.values(item.scores).reduce((a, b) => a + b, 0) / Object.values(item.scores).length
  score += avg

  return score
}
